branch-defaults:
  master:
    environment: mahlzeitv2-env
environment-defaults:
  mahlzeitv3-env:
    branch: null
    repository: null
global:
  application_name: mahlzeitv2
  default_ec2_keyname: awsebglown
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Node.js running
    on 64bit Amazon Linux/3.2.0
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: '360'
  sc: git
  workspace_type: Application


