branch-defaults:
  master:
    environment: mahlzeitv2-env
environment-defaults:
  mahlzeitv3-env:
    branch: null
    repository: null
global:
  application_name: mahlzeitv2
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: '360'
  sc: git
  workspace_type: Application


