branch-defaults:
  master:
    environment: mahlzeit-env
environment-defaults:
  mahlzeit-env:
    branch: null
    repository: null
global:
  application_name: mahlzeit
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v3.2.0 running Node.js
  default_region: eu-central-1
  profile: '360'
  sc: git
