branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: mahlzeitV2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: '360'
  repository: null
  sc: git
  workspace_type: Application
