branch-defaults:
  master:
    environment: mahlzeitv2-env
environment-defaults:
  mahlzeitv3-env:
    branch: null
    repository: null
global:
  application_name: mahlzeitV2
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v3.2.0 running Node.js
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: '360'
  sc: git
  workspace_type: Application


