branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  mahlzeit-env:
    branch: null
    repository: null
global:
  application_name: mahlzeitV2
  branch: null
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v3.2.0 running Node.js
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
